### ISSUE TITLE
API

### ISSUE THREAD

**Issue by pniedzwiedzinski** [dzek69/kalendarz-swiat-nietypowych-ics-google-exporter#1]
Chcę w projekcie wykorzystać kalendarz świąt nietypowych i mam taki pomysł, żeby stworzyć API do świąt nietypowych. Żeby to postawić za darmo to można wrzucić na gh-pages pliki json. Serwować tak będzie można tylko święta stałe, ale myślę że to nie będzie jakiś duży problem.

`/<numer_miesiąca>/<numer_dnia>.json` - taka by była ścieżka do pliku. A w pliku byłaby tablica świąt, jako że zdarza się że jest więcej świąt jednego dnia.

Dodatkowo można dodać do github actions comiesięczne odświeżanie plików.

**Comment by dzek69** [comment]
Brzmi na całkiem spoko pomysł.

Ale, że to repo służy już do exportu do ICS (i nawet ma to w nazwie) stwierdziłem, że lepiej będzie wydzielić pobieranie i parsowanie dat, a osobno zostawić kod eksportowania tutaj.

Do generowania JSON API widziałbym kolejne repo. Do Twojego pomysłu dodałbym generowanie plików JSON dla całego miesiąca i roku.

Jako, że mam też dużo innych rzeczy do roboty - pozostawiam kwestię wydzielenia kodu, który zaproponowałeś w PR w osobne repo (ja i tak mam mało czasu na utrzymywanie tego wszystkiego, co udostępniłem, wiele rzeczy jest w stanie "W.I.P") i podrzucenia mi linka - chętnie zalinkuję je w README. Nie znam też GitHub Actions tak szczerze (chociaż wypadałoby poznać), więc tym bardziej zostawiam to Tobie i tylko podejrzę jak to zrobiłeś (o ile konfiguracja Actions jest widoczna publicznie).

Dzięki za sugestię i zaangażowanie, w tym PRkę 👍.

**Comment by pniedzwiedzinski** [comment]
Racja, nowe repo brzmi bardziej sensownie. Zrobię nowe repo ale skopiuje całą historię commitów z tego repo (żebyś był w współautorach 😉)

**Comment by dzek69** [comment]
Nie ma takiej potrzeby, ale dzięki :) Czekam na info jak będzie gotowe ;)

**Comment by pniedzwiedzinski** [comment]
A dobra, bo wyeksportowałeś to do nowego repo. To świetnie, użyje tamtego jako dependency i powinno śmigać 👍

**Comment by pniedzwiedzinski** [comment]
https://github.com/pniedzwiedzinski/kalendarz-swiat-nietypowych i śmiga 😄

**Comment by dzek69** [comment]
Dzięki 👍 , wystawiłem drobne zmiany i poprawki

Wątek tutaj zamykam, w razie komentarzy pisz pod PRką
